/**
 * Ritual — Datos de preguntas y retos para los 3 juegos
 */

function shuffle(arr) {
  var a = arr.slice();
  for (var i = a.length - 1; i > 0; i--) {
    var j = Math.floor(Math.random() * (i + 1));
    var t = a[i]; a[i] = a[j]; a[j] = t;
  }
  return a;
}
window.RitualShuffle = shuffle;

window.RitualDatos = {
  conexion: {
    suave: [
      "¿Qué es lo primero que notaste de mí cuando nos conocimos?",
      "¿Cuál es un recuerdo nuestro que te hace sonreír solo de pensarlo?",
      "¿Qué cosa pequeña que hago te hace sentir querido/a?",
      "¿En qué momento te sentiste más orgulloso/a de nosotros?",
      "¿Qué lugar compartido te gustaría volver a vivir conmigo?",
      "¿Qué canción o película asociás a nosotros y por qué?",
      "¿Qué detalle mío te enamoró más de lo que imaginabas?",
      "¿Qué versión de nosotros te gusta más: la del inicio o la de ahora? ¿Por qué?",
      "¿Qué momento pequeño nuestro sentís que fue importante sin que lo notáramos?",
      "¿Qué gesto mío te hace sentir elegido/a?",
      "¿Qué parte de mi personalidad sentís que entendés mejor que nadie?",
      "¿Qué cosa nuestra te gustaría que nunca cambiara?",
      "Completar frase: «Me siento más cerca tuyo cuando ______.»",
      "Completar frase: «Una cosa que me gusta de cómo me mirás es ______.»",
      "Completar frase: «Cuando me abrazás siento ______.»",
      "Completar frase: «Algo que quiero que sigamos haciendo siempre es ______.»",
      "Mirame 10 segundos en silencio y decime qué ves.",
      "Decime algo lindo de mí que no tenga que ver con lo físico.",
      "Tomame la mano y contame qué pensabas la primera vez que lo hiciste.",
      "Recordá nuestro primer beso y describilo como si fuera hoy.",
      "Decime un recuerdo nuestro que no suela salir en conversaciones.",
      "¿Qué momento cotidiano conmigo te hace sentir en casa?",
      "¿Qué parte de mi risa te gusta más?",
      "¿Qué recuerdo nuestro te gustaría guardar para siempre tal como fue?",
      "¿Qué costumbre nuestra te da ternura?",
      "¿Qué parte de mí te genera tranquilidad?",
      "¿Qué diferencia entre nosotros te gusta?",
      "¿Qué gesto mío te hace sentir cuidado/a?",
      "¿Qué plan simple conmigo te hace feliz sin mucho esfuerzo?",
      "¿Qué conversación nuestra te dejó pensando lindo después?",
      "¿Qué momento nuestro sentís que fue un punto de unión?",
      "Completar frase: «Con vos me siento más ______.»",
      "Completar frase: «Cuando estamos juntos y pasa algo difícil, me gusta que vos ______.»",
      "Decime algo mío que quizás yo no valoro tanto como debería.",
      "Si tuvieras que describir nuestra energía juntos en una palabra, ¿cuál sería?",
      "¿Qué parte de nuestra historia te gusta contarle a otros?",
    ],
    profundo: [
      "¿Qué miedo tuyo me has contado solo a mí (o te gustaría contarme)?",
      "¿Qué necesidad emocional creés que no estoy viendo todavía?",
      "¿En qué momento sentiste que podías confiar en mí de verdad?",
      "¿Qué cosa que hicimos juntos te cambió o te marcó?",
      "¿Qué te cuesta decirme y por qué?",
      "¿Qué sueño para nuestra relación no hemos hablado aún?",
      "¿Qué parte de vos todavía no me mostraste del todo?",
      "¿En qué momento sentiste que yo no te entendí?",
      "¿Qué emoción te cuesta más compartir conmigo?",
      "¿Qué creés que yo aún no termino de comprender sobre tu forma de amar?",
      "¿Qué inseguridad aparece cuando discutimos?",
      "¿Qué necesitás que haga cuando estás mal y no sabés cómo pedirlo?",
      "¿Qué experiencia pasada influye más en cómo te vinculás hoy?",
      "¿Qué miedo tuyo impacta en nuestra relación?",
      "¿Qué aprendiste del amor antes de conocerme?",
      "¿Qué patrón quisieras romper conmigo?",
      "Completar frase: «Me duele cuando ______.»",
      "Completar frase: «A veces me guardo ______ por miedo a ______.»",
      "Completar frase: «Quisiera que entendieras que para mí es importante ______.»",
      "Completar frase: «Cuando me cierro es porque ______.»",
      "Decime algo que te dio miedo decirme alguna vez.",
      "Contame un pensamiento que tuviste sobre nosotros y no compartiste.",
      "Si hoy tuvieras que pedirme algo importante, ¿qué sería?",
      "Mirame y decime algo honesto aunque no sea cómodo.",
      "Decime qué parte de nuestra relación te gustaría fortalecer.",
      "¿Qué parte de vos siente que todavía se está cuidando conmigo?",
      "¿Qué emoción aparece cuando pensás en un conflicto nuestro?",
      "¿Qué creés que necesito entender mejor de tus silencios?",
      "¿Qué miedo aparece cuando sentís distancia entre nosotros?",
      "¿Qué expectativa sentís que pongo sobre vos, aunque no lo diga?",
      "¿Qué parte de tu pasado todavía influye en cómo reaccionás conmigo?",
      "¿Qué tema evitamos hablar y por qué?",
      "¿Qué parte de nuestra relación necesita más presencia?",
      "¿Qué gesto mío te ayuda a sentir seguridad?",
      "¿Qué parte de mi forma de amar te cuesta más?",
      "Completar frase: «Me siento inseguro/a cuando ______.»",
      "Completar frase: «Cuando discutimos, en el fondo lo que necesito es ______.»",
      "Decime algo que quisieras que yo intuya sin que tengas que pedirlo.",
      "Si tuvieras que explicarme cómo te sentís en este momento de nuestra relación, ¿qué dirías?",
      "¿Qué parte de nosotros querés fortalecer este año?",
    ],
    vulnerable: [
      "¿Qué herida del pasado creés que aún te afecta en esta relación?",
      "¿En qué momento te sentiste más frágil conmigo y qué necesitabas?",
      "¿Qué cosa mía te duele o te cuesta aceptar, y qué harías con eso?",
      "¿Qué necesitás que te diga o que te muestre más a menudo?",
      "¿Qué sacrificio o renuncia sentís que hacés por nosotros y cómo te hace sentir?",
      "Si pudieras pedirme un solo cambio concreto para sentirte más amado/a, ¿cuál sería?",
      "¿Qué parte de vos teme no ser suficiente para mí?",
      "¿Qué herida del pasado sentís que a veces se activa conmigo?",
      "¿Qué te da miedo perder de nosotros?",
      "¿En qué momento te sentiste más frágil conmigo?",
      "¿Qué cosa mía te duele pero te cuesta decir?",
      "¿Qué silencio nuestro pesa más de lo que aparenta?",
      "¿Qué cambio mío te haría sentir más amado/a?",
      "¿Qué necesitás escuchar hoy de mí?",
      "¿Qué parte de nuestra relación te asusta?",
      "¿Qué temor aparece cuando imaginas el futuro juntos?",
      "¿Qué te duele admitir?",
      "¿Qué parte de tu historia todavía estás sanando mientras estamos juntos?",
      "Decime algo que nunca me pediste por miedo.",
      "Decime qué necesitás que vea en vos ahora mismo.",
      "Si mañana todo cambiara, ¿qué sería lo más difícil para vos?",
      "Mirame y decime qué temés que no esté entendiendo.",
      "¿Qué versión tuya querés que acompañe mejor?",
      "Decime algo que te dé vergüenza admitir.",
      "¿Qué sacrificio hiciste por nosotros que nunca hablamos?",
      "¿Qué palabra describe tu amor por mí cuando nadie nos escucha?",
      "¿Qué miedo profundo aparece cuando pensás en perderme?",
      "¿Qué parte de vos siente que no siempre es suficiente?",
      "¿Qué herida creés que a veces descargás en nuestra relación sin querer?",
      "¿Qué silencio tuyo pesa más de lo que muestro?",
      "¿Qué parte de tu historia te da miedo que afecte lo nuestro?",
      "¿Qué parte de mí te activa inseguridades?",
      "¿Qué emoción te supera cuando imaginás un futuro incierto juntos?",
      "¿Qué parte tuya necesita más paciencia de mi parte?",
      "Completar frase: «Si te soy completamente honesto/a, me duele ______.»",
      "Completar frase: «Lo que más temo callar es ______.»",
      "Decime algo que necesitás que cambie para sentirte más seguro/a.",
      "¿Qué parte de tu vulnerabilidad te cuesta más mostrarme?",
      "¿Qué momento nuestro te hizo sentir pequeño/a por dentro?",
      "¿Qué parte de tu amor por mí no siempre sabés cómo expresar?",
      "Si hoy tuvieras que decir una verdad difícil pero necesaria, ¿cuál sería?",
    ],
  },
  picante: {
    nivel1: [
      "Miremosnos a los ojos sin hablar durante un minuto. Quien sonría primero elige el siguiente reto.",
      "Un masaje de un minuto en los hombros. El que recibe dice en voz alta qué le gusta de la mano del otro.",
      "Decirle al otro una cosa que os guste de su cuerpo (que no sea obvia).",
      "Besar al otro en un lugar que no sea la boca. El otro elige el lugar.",
      "Contar un recuerdo en que os hayáis sentido atraídos el uno por el otro.",
      "Acercate lentamente hasta quedar a pocos centímetros. Quédense ahí 10 segundos sin tocarse.",
      "Describí en voz baja algo que te guste del cuerpo del otro sin usar la palabra «lindo/a».",
      "Pasá tus dedos por su brazo lentamente y preguntá: ¿más lento o más rápido?",
      "Mirá su boca mientras habla durante 20 segundos.",
      "Apoyá tu frente en la suya y respiren juntos.",
    ],
    nivel2: [
      "Un beso lento de treinta segundos. Sin prisas.",
      "Susurrar al oído algo que os gustaría hacer juntos esta noche (sin obligación de hacerlo).",
      "El que recibe elige: un beso en el cuello o en la mano. El otro lo hace y mantiene el contacto 10 segundos.",
      "Decir en una frase qué os pone de el/la otro/a hoy, en este momento.",
      "Abrazar fuerte y quedarse así hasta que uno diga «gracias».",
      "Susurrá una fantasía suave que nunca hayan probado (no obligación).",
      "Rozá su cuello sin besar y quedate ahí 5 segundos.",
      "Decí en voz baja dónde te gustaría que te besen ahora.",
      "Tomá su mano y guiala hasta donde quieras que toque (sobre la ropa).",
      "Mantené la mirada mientras te acercás lentamente… y frená antes de besar.",
    ],
    nivel3: [
      "Elegir un deseo que tengan ambos y decirlo en voz alta. El otro solo escucha y responde «te escucho».",
      "Un beso donde el que inicia para cuando quiera; el otro sigue el ritmo.",
      "Mirá a los ojos y decidan juntos si pasan al siguiente reto o lo dejan aquí. No hay respuesta incorrecta.",
      "El que quiera puede pedir un «sí», un «no» o un «ahora no» para algo concreto. El otro responde con honestidad.",
      "Un minuto de contacto: manos, mirada, o lo que elijan. Luego hablar de cómo se sintieron.",
      "Decí exactamente qué te gustaría que pase después… sin actuarlo todavía.",
      "Elegí una palabra clave que signifique «más» y otra que signifique «pausa».",
      "Tocarse las manos mientras describen qué sienten en el cuerpo.",
      "Decir «me gustás así» mirándose fijamente.",
      "Elegir si quieren continuar o simplemente quedarse en la tensión.",
    ],
  },
  eleccion: {
    opcionesA: [
      "Hablar sin filtro",
      "Un beso",
      "Un secreto",
      "Un masaje",
      "Un reto",
      "Una verdad",
    ],
    opcionesB: [
      "Hablar sin filtro",
      "Un beso",
      "Un secreto",
      "Un masaje",
      "Un reto",
      "Una verdad",
    ],
    // Premios por categoría: cada índice = opción; varios premios = se elige uno al azar al coincidir.
    premios: [
      ["Los dos eligen una pregunta del otro y se la hacen. Responde quien quiera primero."],
      [
        "Beso lento 20 segundos.",
        "Beso donde elige quien recibe.",
        "Beso con manos quietas.",
        "Beso sin cerrar los ojos.",
        "Beso que termina cuando uno diga «ya».",
      ],
      ["Cada uno cuenta un deseo que tenga para la pareja (no hace falta cumplirlo ahora)."],
      ["Un minuto de mirada a los ojos. Luego decir en una palabra cómo se sintieron."],
      ["Un reto en común: el que tenga la idea lo dice y el otro puede sumar una condición."],
      ["Una verdad que no hayan dicho antes. Puede ser pequeña o grande."],
    ],
  },
};
