-- Rituales — Expansión de contenido: de 10 a 50 por categoría
-- Agrega 40 rituales por categoría (160 en total)

INSERT INTO public.rituals (category, prompt, challenge, difficulty) VALUES

-- ══════════════════════════════════════════
-- CONEXIÓN (40 nuevos, total: 50)
-- ══════════════════════════════════════════
('conexion', '¿Qué parte de tu infancia quisiste compartir conmigo pero nunca encontraste el momento?', NULL, 2),
('conexion', '¿Cuál es la decisión más importante que tomaste antes de conocerme?', NULL, 2),
('conexion', '¿En qué momento exacto sentiste que yo era alguien especial para vos?', NULL, 1),
('conexion', '¿Qué cosa de tu vida diaria querés que yo conozca mejor?', NULL, 1),
('conexion', '¿Hay algo que siento o pienso de mí mismo/a que vos ves diferente?', NULL, 2),
('conexion', '¿Cuál es el mayor miedo que tenés sobre nosotros dos?', NULL, 3),
('conexion', '¿Qué conversación de nosotros recordás con más claridad?', NULL, 1),
('conexion', '¿Cómo te imaginabas el amor antes de estar conmigo?', NULL, 2),
('conexion', '¿Qué es lo que más cambiaste desde que estamos juntos/as?', NULL, 2),
('conexion', '¿Cuál es la cosa más honesta que podrías decirme sobre cómo te sentís en este momento?', NULL, 3),
('conexion', '¿Qué es lo que más te da miedo perder de nuestra relación?', NULL, 3),
('conexion', '¿Cuándo fue la última vez que me sorprendiste a vos mismo/a?', NULL, 2),
('conexion', '¿Qué versión de mí te cuesta más querer y por qué igual lo hacés?', NULL, 3),
('conexion', '¿Hay algo que le cambiarías a la forma en que empezamos nuestra historia?', NULL, 2),
('conexion', '¿Qué cosa que hacés cuando estás solo/a nunca me mostraste?', NULL, 2),
('conexion', '¿Qué necesitás de mí que nunca terminaste de pedirme?', NULL, 3),
('conexion', '¿Cuál es el logro tuyo que sentís que yo más celebré?', NULL, 1),
('conexion', '¿Qué parte de vos creés que yo no termino de entender?', NULL, 2),
('conexion', '¿Cuándo fue la última vez que te sentiste solo/a estando conmigo?', NULL, 3),
('conexion', '¿Qué valor tuyo sentís que más comparto con vos?', NULL, 1),
('conexion', '¿Qué historia familiar tuya quisieras que yo conociera mejor?', NULL, 2),
('conexion', '¿Qué cosa de nuestra relación te sorprendió que funcionara tan bien?', NULL, 1),
('conexion', '¿Si pudieras cambiar algo de cómo me comunicó con vos, qué sería?', NULL, 2),
('conexion', '¿Cuál es la versión de vos que más querés que yo conozca?', NULL, 2),
('conexion', '¿Qué amistad o relación tuya querés que yo valore más?', NULL, 2),
('conexion', '¿En qué momento sentiste que nuestros valores realmente coincidían?', NULL, 1),
('conexion', '¿Qué cosa de tu trabajo o proyectos quisiste contarme pero no sabías cómo?', NULL, 2),
('conexion', '¿Cuándo fue la primera vez que pensaste "quiero que esta persona esté en mi vida"?', NULL, 1),
('conexion', '¿Qué cosa hacés por mí que sentís que no noto suficiente?', NULL, 2),
('conexion', '¿Cuál es el ritual o hábito nuestro que más valorás?', NULL, 1),
('conexion', '¿Qué es lo que más extrañás de cuando recién empezamos?', NULL, 2),
('conexion', '¿Hay algo que dejaste de hacer desde que estamos juntos/as que extrañás?', NULL, 2),
('conexion', '¿Qué cosa nuestra querés que sigamos haciendo dentro de 10 años?', NULL, 1),
('conexion', '¿Cuál es la pelea o desacuerdo que más te enseñó sobre nosotros?', NULL, 2),
('conexion', '¿Qué parte de mi pasado entendiste mejor con el tiempo?', NULL, 2),
('conexion', '¿Cuándo fue la última vez que me miraste y pensaste "qué suerte que está en mi vida"?', NULL, 1),
('conexion', '¿Qué emoción sentís más frecuentemente y rara vez me contás?', NULL, 3),
('conexion', '¿Cuál es el sueño que tenés que sentís que yo podría ayudarte a cumplir?', NULL, 2),
('conexion', '¿Qué cosa mía te genera ternura aunque no me lo decís?', NULL, 1),
('conexion', '¿Cuál es la pregunta que más miedo te daría hacerme?', NULL, 3),

-- ══════════════════════════════════════════
-- DIVERSIÓN (40 nuevos, total: 50)
-- ══════════════════════════════════════════
('diversion', '¿Cuál sería nuestra canción perfecta para bailar en la cocina a las 11 de la noche?', NULL, 1),
('diversion', '¿Si pudiéramos ser personajes de cualquier película, quiénes seríamos?', NULL, 1),
('diversion', '¿Cuál es el plan ridículo que tengo ganas de que hagamos y nunca propuse?', 'Proponelo ahora.', 2),
('diversion', '¿Qué comida nos define como pareja?', NULL, 1),
('diversion', '¿Si tuviéramos que describir nuestra relación con un meme, cuál sería?', NULL, 1),
('diversion', '¿Cuál sería nuestro superpoder de pareja si fuéramos un dúo de superhéroes?', NULL, 1),
('diversion', '¿Qué cosa que hacemos juntos te parece que a los demás les parecería rarísima?', NULL, 1),
('diversion', '¿Si nuestra relación fuera una serie de Netflix, cuál sería el título y de qué género?', NULL, 1),
('diversion', '¿Cuál es el chiste interno nuestro que más te hace reír?', NULL, 1),
('diversion', '¿En qué momento de nuestra historia te reíste hasta llorar?', NULL, 1),
('diversion', '¿Si tuviéramos que competir en un reality show juntos, en cuál ganaríamos?', NULL, 1),
('diversion', '¿Cuál es el plan de fin de semana perfecto que todavía no hicimos?', NULL, 1),
('diversion', '¿Qué personaje de una serie o película te recuerda a mí?', NULL, 1),
('diversion', '¿Si pudiéramos tener una mascota imaginaria y ridícula, qué sería?', NULL, 1),
('diversion', '¿Cuál es la apuesta que le harías a alguien sobre mí y estás seguro/a que ganarías?', NULL, 1),
('diversion', '¿Qué deporte o actividad que nunca hicimos juntos creés que nos quedaría perfecto?', 'Agendá probarlo.', 2),
('diversion', '¿Si pudieras diseñar nuestro día perfecto sin límites de dinero, cómo sería?', NULL, 1),
('diversion', '¿Cuál es la cosa más ridícula que dijiste o hiciste delante mío y ahora te da risa?', NULL, 1),
('diversion', '¿Qué sabor de helado me representaría y por qué?', NULL, 1),
('diversion', '¿Si pudiéramos vivir en cualquier ciudad del mundo, en cuál estaríamos?', NULL, 1),
('diversion', '¿Cuál es la peor película que vimos juntos y por qué la terminamos igual?', NULL, 1),
('diversion', '¿Qué cosa nuestra convertirías en una tradición oficial de pareja?', NULL, 1),
('diversion', '¿Si tuviéramos que escribir una canción sobre nuestra relación, cuál sería el primer verso?', 'Inventá el verso ahora.', 2),
('diversion', '¿Cuál es el viaje que más ilusión te haría hacer conmigo y por qué?', NULL, 1),
('diversion', '¿Si pudiéramos intercambiar personalidades por un día, qué aprenderías de mí?', NULL, 2),
('diversion', '¿Cuál es la habilidad culinaria que querés que aprendamos juntos?', 'Elegí una receta y cocínenla esta semana.', 2),
('diversion', '¿Qué juego de mesa o de cartas nos haría más competitivos y por qué?', NULL, 1),
('diversion', '¿Si hiciéramos un podcast juntos, de qué trataría?', NULL, 1),
('diversion', '¿Cuál es el desafío físico o aventura que te gustaría hacer conmigo?', NULL, 2),
('diversion', '¿Qué cosa que hacés perfectamente yo hago pésimo?', NULL, 1),
('diversion', '¿Si pudiéramos tener una cena con cualquier pareja famosa (real o ficticia), quiénes serían?', NULL, 1),
('diversion', '¿Cuál es nuestra inside joke que nunca le explicarías a nadie?', NULL, 1),
('diversion', '¿Qué cosa de nuestra rutina le parecería fascinante a alguien que nunca nos conoció?', NULL, 1),
('diversion', '¿Si tuviéramos que hacer un video viral juntos, de qué sería?', NULL, 1),
('diversion', '¿Cuál es el lugar más raro o inesperado donde vivimos algo especial juntos?', NULL, 1),
('diversion', '¿Qué colección o hobby ridículo podríamos empezar juntos?', NULL, 1),
('diversion', '¿Si pudiéramos volver a un año de nuestra vida, a cuál iríamos y qué cambiaríamos?', NULL, 2),
('diversion', '¿Cuál es el apodo que nunca te dije pero en mi cabeza te tengo puesto?', 'Decílo ahora.', 2),
('diversion', '¿Qué cosa de nuestra convivencia (real o imaginaria) sería el tema de pelea más ridículo?', NULL, 1),
('diversion', '¿Si pudiéramos hacer una "bucket list de pareja", cuál sería el primer punto?', 'Escriban 5 cosas juntos.', 2),

-- ══════════════════════════════════════════
-- INTIMIDAD (40 nuevos, total: 50)
-- ══════════════════════════════════════════
('intimidad', '¿Cuándo fue la última vez que me miraste y sentiste algo fuerte por dentro?', NULL, 2),
('intimidad', '¿Qué cosa que hago inconscientemente te genera atracción?', NULL, 2),
('intimidad', '¿Hay algo que te gustaría que cambiáramos en la forma en que nos demostramos afecto?', NULL, 2),
('intimidad', '¿Cuándo te sentís más conectado/a conmigo emocionalmente?', NULL, 2),
('intimidad', '¿Qué gesto pequeño mío te genera más ternura?', NULL, 1),
('intimidad', '¿Cuándo fue la última vez que te sorprendí de una manera que te gustó?', NULL, 2),
('intimidad', '¿Qué cosa nuestra te genera más seguridad emocional?', NULL, 2),
('intimidad', '¿Hay algo que querés que yo sepa sobre cómo te gusta sentirte querido/a?', NULL, 2),
('intimidad', '¿Cuándo te sentís más visto/a por mí?', NULL, 2),
('intimidad', '¿Qué momento de los últimos días te hubiera gustado que durara más?', NULL, 2),
('intimidad', '¿Qué cosa de mi presencia física te calma o te da paz?', NULL, 2),
('intimidad', '¿Hay algo que exploraron juntos que te sorprendió gratamente?', NULL, 2),
('intimidad', '¿Cuándo fue la última vez que te sentiste completamente presente conmigo?', NULL, 2),
('intimidad', '¿Qué cosa querés que yo recuerde hacer más seguido?', NULL, 2),
('intimidad', '¿Hay algún momento del día en que me extrañás más?', NULL, 1),
('intimidad', '¿Qué es lo que más te gusta de dormirte o despertarte conmigo?', NULL, 1),
('intimidad', '¿Cuándo sentís que nuestra conexión está en su mejor punto?', NULL, 2),
('intimidad', '¿Qué cosa nueva te gustaría explorar juntos emocionalmente?', NULL, 2),
('intimidad', '¿Hay algo que te dé vergüenza pedirme aunque sepas que lo haría con gusto?', NULL, 3),
('intimidad', '¿Cuándo fue la última vez que un abrazo mío te cambió el estado de ánimo?', NULL, 1),
('intimidad', '¿Qué parte de mi cuerpo o de mi forma de ser te genera más ternura?', NULL, 2),
('intimidad', '¿Hay algo de nuestra vida íntima que querés que hablemos más abiertamente?', NULL, 3),
('intimidad', '¿Cuándo te sentís más cómodo/a siendo completamente vos mismo/a conmigo?', NULL, 2),
('intimidad', '¿Qué cosa mía te hace sentir que estás en casa?', NULL, 1),
('intimidad', '¿Cuándo fue la última vez que sentiste mariposas estando conmigo?', NULL, 2),
('intimidad', '¿Qué es lo que más valorás de nuestra intimidad emocional?', NULL, 2),
('intimidad', '¿Hay algo que siempre quisiste decirme pero te costó encontrar las palabras?', NULL, 3),
('intimidad', '¿Cuándo sentís que me necesitás más y no siempre me lo pedís?', NULL, 3),
('intimidad', '¿Qué momento nuestro guardarías en una foto mental para siempre?', NULL, 1),
('intimidad', '¿Hay algo de nuestra relación que te parece que los demás envidian?', NULL, 2),
('intimidad', '¿Qué cosa de cómo te quiero te hace sentir más único/a?', NULL, 2),
('intimidad', '¿Cuándo fue la última vez que sentiste que me importabas profundamente?', NULL, 2),
('intimidad', '¿Qué cosa tuya considero perfectamente imperfecta y vos no la ves así?', NULL, 2),
('intimidad', '¿Hay algo de tu pasado que sientas que yo acepto sin juzgarte?', NULL, 2),
('intimidad', '¿Cuándo te sentís más frágil y cómo preferís que yo esté en esos momentos?', NULL, 3),
('intimidad', '¿Qué palabra o frase mía te llega más hondo cuando la digo?', NULL, 2),
('intimidad', '¿Hay algo que quisieras que viviéramos juntos antes de que pase mucho tiempo?', NULL, 2),
('intimidad', '¿Cuándo fue la última vez que lloraste o estuviste a punto de llorar de emoción por algo nuestro?', NULL, 2),
('intimidad', '¿Qué cosa de nuestra historia de amor te parece que merece una película?', NULL, 1),
('intimidad', '¿Cuándo sentís que el amor que nos tenemos creció más?', NULL, 2),

-- ══════════════════════════════════════════
-- RETO (40 nuevos, total: 50)
-- ══════════════════════════════════════════
('reto', '¿Cuál es una meta que tenés este año y yo puedo ayudarte a cumplir? Decime cómo.', NULL, 2),
('reto', 'Escribí tres cosas específicas que el otro hizo bien esta semana.', 'Leanselas en voz alta.', 2),
('reto', 'Tomá una foto de algo que te recuerda al otro y compartila con una explicación.', NULL, 1),
('reto', '¿Cuál es una costumbre tuya que querés cambiar? Pedime apoyo para lograrlo.', NULL, 2),
('reto', 'Sin usar el celular, tengan una conversación de 10 minutos sobre algo que nunca hablen.', 'Elijan el tema juntos.', 3),
('reto', '¿Cuál es algo que aprendiste de mí sin que yo te lo haya enseñado explícitamente?', NULL, 2),
('reto', 'Escribí una lista de 5 cosas que te gustan de nuestra vida juntos/as ahora mismo.', 'Compartanlas.', 1),
('reto', '¿Cuál es el mayor obstáculo que tienen como pareja y qué paso pequeño podrían dar hoy?', NULL, 3),
('reto', 'Planeá una sorpresa para el otro que puedas ejecutar esta semana. Anunciá solo que viene.', NULL, 2),
('reto', '¿Cuándo fue la última vez que hicieron algo nuevo juntos? Planeen algo para los próximos 7 días.', 'Pongan fecha y hora.', 2),
('reto', 'Cada uno dice una cosa que el otro hace que lo hace más fácil vivir. Sin repetir.', NULL, 1),
('reto', '¿Cuál es un hábito que querés que adoptemos como pareja?', 'Acuerden probarlo por 7 días.', 2),
('reto', 'Mandale un mensaje de voz de 60 segundos diciéndole algo que sentís pero rara vez decís.', NULL, 3),
('reto', '¿Qué es lo que más querés lograr juntos en los próximos 6 meses?', 'Escribanlo en algún lugar.', 2),
('reto', 'Elegí una cosa que el otro hace que querés que siga haciendo siempre. Decíselo.', NULL, 1),
('reto', '¿Cuál es una conversación difícil que venís postergando? ¿Qué necesitás para tenerla?', NULL, 3),
('reto', 'Hagan una lista de 3 lugares que quieren conocer juntos. Elijan uno y busquen cuándo ir.', NULL, 2),
('reto', '¿Cuál es algo que te pesa de nuestra dinámica y querés que cambie?', NULL, 3),
('reto', 'Describí el mejor día que podrían tener juntos este mes con menos de $50.', 'Organícenlo.', 2),
('reto', '¿Cuál es un miedo que tenés sobre el futuro que nunca terminaste de contarme?', NULL, 3),
('reto', 'Elijan un libro, podcast o documental para consumir juntos este mes. Decidan cuál.', NULL, 1),
('reto', '¿Qué cosa de tu rutina diaria querés que yo sea más parte?', NULL, 2),
('reto', 'Escribí lo que más agradecés del otro en este momento específico de su vida.', NULL, 1),
('reto', '¿Cuál es una limitación tuya que querés trabajar y cómo puedo acompañarte?', NULL, 3),
('reto', 'Cada uno cuenta un error que cometió en la relación y lo que aprendió de él.', NULL, 3),
('reto', '¿Cuál es la próxima celebración que quieren hacer juntos aunque sea pequeña?', 'Fijen fecha.', 1),
('reto', 'Hagan un "detox de celulares" por la próxima hora. Sin pantallas. Solo ustedes dos.', NULL, 3),
('reto', '¿Cuál es algo que hacés solo/a que te gustaría empezar a compartir conmigo?', NULL, 2),
('reto', 'Escribí una carta corta al otro explicando por qué elegirías estar con él/ella de nuevo.', 'Leanselas.', 3),
('reto', '¿Cuándo fue la última vez que hicieron algo solo para el otro sin que lo pidiera?', 'Planeá hacerlo esta semana.', 2),
('reto', '¿Qué es lo que más necesitás de mí cuando estás estresado/a?', NULL, 2),
('reto', 'Elijan una actividad física para hacer juntos esta semana. Pónganse de acuerdo ahora.', NULL, 1),
('reto', '¿Cuál es algo que creés que el otro necesita escuchar pero nadie le dice?', NULL, 3),
('reto', 'Compartan una foto de infancia y cuenten algo que esa foto representa para ustedes.', NULL, 2),
('reto', '¿Qué es lo que más te enorgullece de nosotros como pareja?', NULL, 1),
('reto', 'Hagan una lista de 5 cosas que quieren mejorar juntos como pareja este año.', 'Guárdenla.', 2),
('reto', '¿Cuál es algo que te gustaría que hiciéramos diferente la próxima vez que tengamos un conflicto?', NULL, 3),
('reto', 'Elegí un momento de la semana que sea "nuestro" — sin teléfonos, sin distracciones.', 'Acuerden cuándo.', 2),
('reto', '¿Cuál es el recuerdo que más te gustaría recrear con el otro?', 'Planeen cómo hacerlo.', 2),
('reto', '¿Qué le dirías a la versión de vos de hace 5 años sobre lo que encontraste en esta persona?', NULL, 3);
